name: go-module

on:
  push:
    tags:
      - "*"

jobs:
  pushJob:
    runs-on: self-hosted
    if: github.event_name == 'push'
    steps:
      - name: push to sub repo
        run: |
          cd C:\Users\clark\Documents\codes\go\go-func\
          git checkout v0
          git push -u origin v0
